# Generated by Django 3.2.15 on 2022-09-10 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2, verbose_name='country name')),
            ],
            options={
                'verbose_name': 'Country News',
                'verbose_name_plural': 'Countries News',
            },
        ),
        migrations.CreateModel(
            name='News_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'News Category ',
                'verbose_name_plural': 'News Categories',
            },
        ),
        migrations.CreateModel(
            name='News_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('content', models.CharField(max_length=250, verbose_name='Content')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('publishedAt', models.CharField(max_length=30, verbose_name='Published at')),
                ('url', models.SlugField(max_length=250)),
                ('urlToImage', models.SlugField(max_length=250, verbose_name='Image url')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.news_categories')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_app.country_news')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ('id',),
            },
        ),
    ]
